# Generated by Django 2.1.7 on 2019-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_mytaskcomment_teamtaskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='status',
            field=models.CharField(default='Planned', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
